[package]
name = "serde-xmlparser"
version = "0.0.1"
authors = ["Jack Shih <i@kshih.com>"]
edition = "2018"

[dependencies]
serde = "*"
xmlparser = "*"

[lib]
name = "serde_xmlparser"
path = "src/lib.rs"