[package]
name = "carrier"
version = "0.1.0"
authors = ["Jack Shih <develop@kshih.com>"]
edition = "2018"

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
serde-xml-rs = "*"
reqwest = "*"