[package]
name = "serde-quick-xml"
version = "0.1.0"
authors = ["kshih <develop@kshih.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
