[package]
name = "serde-quick-xml"
version = "0.0.1"
authors = ["Jack Shih <i@kshih.com>"]
edition = "2018"

[dependencies]
serde = "*"
quick-xml = "*"

[lib]
name = "serde_quick_xml"
path = "src/lib.rs"