name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Config env
      run: mv .env.example .env
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
